// <auto-generated />
using System;
using Invoice.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251004110023_AddRelation_OtherExpense_ExpenseCategory")]
    partial class AddRelation_OtherExpense_ExpenseCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Core.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PartyId")
                        .HasColumnType("int");

                    b.Property<string>("branchID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("buildingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("governate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("regionCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.DocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTimeIssued")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeReceived")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ImportedItemId")
                        .HasColumnType("int");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IssuerId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeVersionName")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ImportedItemId");

                    b.HasIndex("IssuerId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryType = "مصروفات عمومية"
                        },
                        new
                        {
                            Id = 2,
                            CategoryType = "مصروفات تشغيلية"
                        },
                        new
                        {
                            Id = 3,
                            CategoryType = "رسوم"
                        },
                        new
                        {
                            Id = 4,
                            CategoryType = "تأمينات"
                        },
                        new
                        {
                            Id = 5,
                            CategoryType = "مشتريات"
                        },
                        new
                        {
                            Id = 6,
                            CategoryType = "م.خارجيه"
                        },
                        new
                        {
                            Id = 7,
                            CategoryType = "م.تسوقيه"
                        },
                        new
                        {
                            Id = 8,
                            CategoryType = "أخرى"
                        });
                });

            modelBuilder.Entity("Invoice.Core.Model.ExternalExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EPaymentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImportTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReleaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ExternalExpenses", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.ImportedItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ImportedItems", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentModelId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemMappingId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("itemCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("itemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("netTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("salesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalTaxableFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unitType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("valueDifference")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentModelId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("ItemMappingId");

                    b.ToTable("InvoiceLines", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.ItemCodeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("ItemMappings", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.OtherExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BankCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExpenseCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.ToTable("OtherExpenses", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.Party", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PartyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Parties", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.TaxTotal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DocumentModelId")
                        .HasColumnType("int");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentModelId");

                    b.ToTable("TaxTotals", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.TaxableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId");

                    b.ToTable("TaxableItems", (string)null);
                });

            modelBuilder.Entity("Invoice.Core.Model.Address", b =>
                {
                    b.HasOne("Invoice.Core.Model.Party", "Party")
                        .WithOne("Address")
                        .HasForeignKey("Invoice.Core.Model.Address", "PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");
                });

            modelBuilder.Entity("Invoice.Core.Model.DocumentModel", b =>
                {
                    b.HasOne("Invoice.Core.Model.ExpenseCategory", "ExpenseCategory")
                        .WithMany("Documents")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Invoice.Core.Model.ImportedItem", "ImportedItem")
                        .WithMany("Documents")
                        .HasForeignKey("ImportedItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Invoice.Core.Model.Party", "Issuer")
                        .WithMany("IssuedDocuments")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Invoice.Core.Model.Party", "Receiver")
                        .WithMany("ReceivedDocuments")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ImportedItem");

                    b.Navigation("Issuer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Invoice.Core.Model.InvoiceLine", b =>
                {
                    b.HasOne("Invoice.Core.Model.DocumentModel", "DocumentModel")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("DocumentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Invoice.Core.Model.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId");

                    b.HasOne("Invoice.Core.Model.ItemCodeConfig", "ItemMapping")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("ItemMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Invoice.Core.Model.UnitValue", "unitValue", b1 =>
                        {
                            b1.Property<int>("InvoiceLineId")
                                .HasColumnType("int");

                            b1.Property<decimal>("AmountEGP")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("AmountSold")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("CurrencyExchangeRate")
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("CurrencySold")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<int>("Id_PK")
                                .HasColumnType("int");

                            b1.HasKey("InvoiceLineId");

                            b1.ToTable("InvoiceLines");

                            b1.WithOwner("InvoiceLine")
                                .HasForeignKey("InvoiceLineId");

                            b1.Navigation("InvoiceLine");
                        });

                    b.Navigation("DocumentModel");

                    b.Navigation("ExpenseCategory");

                    b.Navigation("ItemMapping");

                    b.Navigation("unitValue")
                        .IsRequired();
                });

            modelBuilder.Entity("Invoice.Core.Model.OtherExpense", b =>
                {
                    b.HasOne("Invoice.Core.Model.ExpenseCategory", "ExpenseCategory")
                        .WithMany("OtherExpenses")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseCategory");
                });

            modelBuilder.Entity("Invoice.Core.Model.TaxTotal", b =>
                {
                    b.HasOne("Invoice.Core.Model.DocumentModel", "DocumentModel")
                        .WithMany("TaxTotals")
                        .HasForeignKey("DocumentModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentModel");
                });

            modelBuilder.Entity("Invoice.Core.Model.TaxableItem", b =>
                {
                    b.HasOne("Invoice.Core.Model.InvoiceLine", "InvoiceLine")
                        .WithMany("TaxableItems")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceLine");
                });

            modelBuilder.Entity("Invoice.Core.Model.DocumentModel", b =>
                {
                    b.Navigation("InvoiceLines");

                    b.Navigation("TaxTotals");
                });

            modelBuilder.Entity("Invoice.Core.Model.ExpenseCategory", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("OtherExpenses");
                });

            modelBuilder.Entity("Invoice.Core.Model.ImportedItem", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Invoice.Core.Model.InvoiceLine", b =>
                {
                    b.Navigation("TaxableItems");
                });

            modelBuilder.Entity("Invoice.Core.Model.ItemCodeConfig", b =>
                {
                    b.Navigation("InvoiceLines");
                });

            modelBuilder.Entity("Invoice.Core.Model.Party", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("IssuedDocuments");

                    b.Navigation("ReceivedDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
